minimum_pre_commit_version: '2.9.0'
repos:
- repo: https://github.com/Zac-HD/shed
  rev: 0.10.7
  hooks:
    - id: shed
      # args: [--refactor, --py39-plus]
      types_or: [python, pyi, markdown, rst]